---
- name: "FILESYSTEM on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    # host_name: all
  collections:
    ibm.power_aix

  tasks:
    - name: Remove a NFS filesystem
      filesystem:
        filesystem: "{{mount_dir_value}}"
        state: absent
        rm_mount_point: true
