---
- name: "MOUNT on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    # host_name: all
    # mount_dir_value: /mnt/testfs
  collections:
    ibm.power_aix

  tasks:
    - name: Mount filesystems
      mount:
        state: mount
        mount_dir: "{{mount_dir_value}}"
