---
- name: "INSTALLP uninstall on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    # host_name: all
    # device_name: /dev/rmt0.1
  collections:
    - ibm.power_aix
  tasks:

    - name: Uninstall a fileset
      installp:
        action: deinstall
        install_list: "{{install_list_value}}"
