---
- name: "MOUNT on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    # host_name: all
  collections:
    ibm.power_aix

  tasks:
    - name: Unmount all remote filesystems
      mount:
        state: umount
        mount_all: remote
        force: True
